name: Tetsuro
favicon: null
layout_spectrum: 0.733721372205764
typography_spectrum: 0.518822630867362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4943906518165022
  lightness: 0.03748142835684121
  saturation: 0.9292332981713116
  rhythmicContrast: 0.8254219212103635
purpose: []
